#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: ORDER-SERVICE
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order/**
#
##eureka:
##  client:
##    register-with-eureka: true
##    fetch-registry: true
##    service-url:
##      defaultZone: 'http://localhost:8761/eureka/'
##  instance:
##    hostname: localhost
#
#eureka:
#  client:
#    register-with-eureka: true   # Register this service with Eureka
#    fetch-registry: true         # Fetch registry information from Eureka
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true       # 🔥 Use IP instead of hostname (prevents hostname resolution issues)
#    hostname: localhost           # Explicitly defining hostname
#    instance-id: ${spring.application.name}:${server.port}  # Unique instance ID (useful for multiple instances)
#
#
#
#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  web:
    exposure:
      include: gateway

server:
  port: 8989  # API Gateway runs on port 8989

spring:
  application:
    name: API-GATEWAY  # Ensure it matches the service name in Eureka
#  cloud:
#    gateway:
#      routes:
#        - id: ORDER-SERVICE
#          uri: lb://ORDER-SERVICE  # Load balance request to ORDER-SERVICE
#          predicates:
#            - Path=/order/**  # Matches requests to /order/**
#          filters:
#            - RewritePath=/order/(?<segment>.*), /${segment}  # Proper YAML syntax

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
  instance:
    prefer-ip-address: true  # Use IP instead of hostname

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: DEBUG



