management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  web:
    exposure:
      include: gateway

server:
  port: 8989  # API Gateway runs on port 8989

spring:
  application:
    name: API-GATEWAY  # Ensure it matches the service name in Eureka

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
#  instance:
#    prefer-ip-address: true  # Use IP instead of hostname

  config:
    import:
    - configserver:http://localhost:8888/



logging:  
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

